-- +goose Up
CREATE TABLE users (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), singleton boolean NOT NULL DEFAULT true UNIQUE CHECK(singleton),
 username text NOT NULL UNIQUE, password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE settings (user_id uuid PRIMARY KEY REFERENCES users ON DELETE CASCADE, timezone text NOT NULL DEFAULT 'Europe/Madrid', language text NOT NULL DEFAULT 'es', week_start integer NOT NULL DEFAULT 1 CHECK(week_start IN(0,1)), hour_format text NOT NULL DEFAULT '24' CHECK(hour_format IN('12','24')), date_format text NOT NULL DEFAULT 'DD/MM/YYYY' CHECK(date_format IN('DD/MM/YYYY','YYYY-MM-DD')), theme text NOT NULL DEFAULT 'system' CHECK(theme IN('light','dark','system')), default_sort text NOT NULL DEFAULT 'manual' CHECK(default_sort IN('manual','date','priority','created','name')), browser_notifications boolean NOT NULL DEFAULT false);
CREATE TABLE projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL CHECK(length(trim(name)) BETWEEN 1 AND 200), description text NOT NULL DEFAULT '', color text NOT NULL DEFAULT '#15836b', icon text NOT NULL DEFAULT 'folder', parent_project_id uuid REFERENCES projects ON DELETE SET NULL, position double precision NOT NULL DEFAULT 1024, favorite boolean NOT NULL DEFAULT false, archived boolean NOT NULL DEFAULT false, default_view text NOT NULL DEFAULT 'list' CHECK(default_view='list'), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(parent_project_id IS DISTINCT FROM id));
CREATE TABLE sections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects ON DELETE CASCADE, name text NOT NULL CHECK(length(trim(name)) BETWEEN 1 AND 200), position double precision NOT NULL DEFAULT 1024, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL CHECK(length(trim(title)) BETWEEN 1 AND 500), description text NOT NULL DEFAULT '', project_id uuid REFERENCES projects ON DELETE SET NULL, section_id uuid REFERENCES sections ON DELETE SET NULL, parent_task_id uuid REFERENCES tasks ON DELETE CASCADE, priority integer NOT NULL DEFAULT 4 CHECK(priority BETWEEN 1 AND 4), due_date date, due_time time, position double precision NOT NULL DEFAULT 1024, status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','completed')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, CHECK(due_time IS NULL OR due_date IS NOT NULL), CHECK(parent_task_id IS DISTINCT FROM id), CHECK((status='completed')=(completed_at IS NOT NULL)));
CREATE INDEX tasks_schedule ON tasks(due_date,due_time) WHERE status='pending';
CREATE INDEX tasks_project ON tasks(project_id,section_id,position);
CREATE INDEX tasks_parent ON tasks(parent_task_id);
CREATE TABLE labels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE CHECK(length(trim(name)) BETWEEN 1 AND 100), color text NOT NULL DEFAULT '#15836b', favorite boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE task_labels(task_id uuid NOT NULL REFERENCES tasks ON DELETE CASCADE,label_id uuid NOT NULL REFERENCES labels ON DELETE CASCADE, PRIMARY KEY(task_id,label_id));
CREATE TABLE task_completions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_id uuid NOT NULL REFERENCES tasks ON DELETE CASCADE, scheduled_for date, completed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE activity_log(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_id uuid REFERENCES tasks ON DELETE SET NULL, event text NOT NULL, title text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
-- +goose Down
DROP TABLE activity_log,task_completions,task_labels,labels,tasks,sections,projects,settings,sessions,users;
